name: build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Test with Pytest
      run: pytest --cov=servifier --cov-config .coveragerc --cov-report=xml
    - name: Upload coverage report to Code Climate
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: 1b01f1376571426e6f792267a07871b57834b1e250e9352eb615d0a5b45a03d9

